set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides ",*:Smulx=\\E[4::%p1%dm"
set -ga terminal-overrides ",*:Setulc=\\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d::m"
set -g status-position top

unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

unbind %
bind '\' split-window -h -c '#={pane_current_path}'

unbind '"'
bind - split-window -v -c '#={pane_current_path}'

# new window 
bind c new-window -c '#={pane_current_path}'

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r h resize-pane -L 5
bind -r l resize-pane -R 5

bind -r m resize-pane -Z

# copy nvim-movements
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind r 
# tmux source-file ~/.tmux.conf \;
bind r source-file ~/.tmux.conf

set -g mouse on
set-window-option -g mode-keys vi 

# start from 1, not 0
set-option -g base-index 1
# re-number when closing windows
set-option -g renumber-windows on

set -s escape-time 0
set -g focus-events on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux#v2.3.0'

# Configure Catppuccin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "basic"

set -g window-status-separator ""  # Removes the space between windows
set -g @catppuccin_window_current_text_color "#{@thm_surface_1}"
set -g @catppuccin_window_current_number_color "#{@thm_peach}"
set -g @catppuccin_window_current_text " #{b:pane_current_path}"

set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_default_text "#W" # show path for active panes, fallback to app name
set -g @catppuccin_window_number_color "#{@thm_lavender}"

set -g @catppuccin_status_background "default"
set -g @catppuccin_window_current_background "default"
set -g @catppuccin_window_default_background "default"

set -g status-left "#[fg=#{@thm_green}]#[reverse]█#[noreverse]#S "
set -g status-right "#[fg=#{@thm_peach}] bachng #[fg=#{@thm_overlay_0}]• #[fg=#{@thm_blue}] %H:%M #[fg=#{@thm_overlay_0}]• #[fg=#{@thm_lavender}]%d-%b-%y #[fg=#{@thm_lavender}]#[reverse]█"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

set -g status-style bg=default
set -g status-interval 15
set -g status-right-length 80

set -g status on
